# Site settings
title: A Place Called Up Blog
email: info@aplacecalledup.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://upconsulting.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
